/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rxonda.hazelcast.spi.consul;

import com.hazelcast.config.properties.PropertyDefinition;
import com.hazelcast.logging.ILogger;
import com.hazelcast.spi.discovery.DiscoveryNode;
import com.hazelcast.spi.discovery.DiscoveryStrategy;
import com.hazelcast.spi.discovery.DiscoveryStrategyFactory;
import org.springframework.cloud.client.discovery.DiscoveryClient;
import org.springframework.cloud.client.serviceregistry.Registration;
import org.springframework.cloud.client.serviceregistry.ServiceRegistry;

import java.util.Arrays;
import java.util.Collection;
import java.util.Map;

import static com.rxonda.hazelcast.spi.consul.HzSpringCloudConsulDiscoveryStrategyProperties.*;

public class HzSpringCloudConsulDiscoveryStrategyFactory implements DiscoveryStrategyFactory {

    private DiscoveryClient discoveryClient;

    private ServiceRegistry<Registration> serviceRegistry;

    public HzSpringCloudConsulDiscoveryStrategyFactory(DiscoveryClient discoveryClient, ServiceRegistry<Registration> serviceRegistry) {
        this.discoveryClient = discoveryClient;
        this.serviceRegistry = serviceRegistry;
    }

    @Override
    public Class<? extends DiscoveryStrategy> getDiscoveryStrategyType() {
        return HzSpringCloudConsulDiscoveryStrategy.class;
    }

    @Override
    public DiscoveryStrategy newDiscoveryStrategy(DiscoveryNode discoveryNode, ILogger iLogger, Map<String, Comparable> properties) {
        return new HzSpringCloudConsulDiscoveryStrategy(discoveryClient, serviceRegistry, discoveryNode, iLogger, properties);
    }

    @Override
    public Collection<PropertyDefinition> getConfigurationProperties() {
        return Arrays.asList(
                APPLICATION_SCOPE, TAGS, CHECK_INTERVAL, PREFER_PUBLIC_IP, DISCOVERY_DELAY, BI_PORT
        );
    }
}
